# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget gdcmCommon gdcmDICT gdcmDSED gdcmIOD gdcmMSFF gdcmMEXD gdcmjpeg8 gdcmjpeg12 gdcmjpeg16 gdcmexpat gdcmopenjp2 gdcmcharls gdcmmd5 gdcmzlib socketxx)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target gdcmCommon
add_library(gdcmCommon SHARED IMPORTED)

set_target_properties(gdcmCommon PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr"
)

# Create imported target gdcmDICT
add_library(gdcmDICT SHARED IMPORTED)

# Create imported target gdcmDSED
add_library(gdcmDSED SHARED IMPORTED)

set_target_properties(gdcmDSED PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmCommon"
)

# Create imported target gdcmIOD
add_library(gdcmIOD SHARED IMPORTED)

set_target_properties(gdcmIOD PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmDSED;gdcmCommon"
)

# Create imported target gdcmMSFF
add_library(gdcmMSFF SHARED IMPORTED)

set_target_properties(gdcmMSFF PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmIOD;gdcmDSED;gdcmDICT"
)

# Create imported target gdcmMEXD
add_library(gdcmMEXD SHARED IMPORTED)

# Create imported target gdcmjpeg8
add_library(gdcmjpeg8 SHARED IMPORTED)

# Create imported target gdcmjpeg12
add_library(gdcmjpeg12 SHARED IMPORTED)

# Create imported target gdcmjpeg16
add_library(gdcmjpeg16 SHARED IMPORTED)

# Create imported target gdcmexpat
add_library(gdcmexpat SHARED IMPORTED)

# Create imported target gdcmopenjp2
add_library(gdcmopenjp2 SHARED IMPORTED)

# Create imported target gdcmcharls
add_library(gdcmcharls SHARED IMPORTED)

# Create imported target gdcmmd5
add_library(gdcmmd5 SHARED IMPORTED)

# Create imported target gdcmzlib
add_library(gdcmzlib SHARED IMPORTED)

# Create imported target socketxx
add_library(socketxx SHARED IMPORTED)

set_target_properties(socketxx PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr"
)

# Import target "gdcmCommon" for configuration "Debug"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmCommon.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmmd5"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmCommon.dll"
  )

# Import target "gdcmDICT" for configuration "Debug"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmDICT.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmDICT.dll"
  )

# Import target "gdcmDSED" for configuration "Debug"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmDSED.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmzlib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmDSED.dll"
  )

# Import target "gdcmIOD" for configuration "Debug"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIOD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmexpat"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIOD.dll"
  )

# Import target "gdcmMSFF" for configuration "Debug"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMSFF.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjp2;gdcmcharls"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMSFF.dll"
  )

# Import target "gdcmMEXD" for configuration "Debug"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;socketxx"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXD.dll"
  )

# Import target "gdcmjpeg8" for configuration "Debug"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg8.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg8.dll"
  )

# Import target "gdcmjpeg12" for configuration "Debug"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg12.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg12.dll"
  )

# Import target "gdcmjpeg16" for configuration "Debug"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg16.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmjpeg16.dll"
  )

# Import target "gdcmexpat" for configuration "Debug"
set_property(TARGET gdcmexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmexpat PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmexpat.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmexpat.dll"
  )

# Import target "gdcmopenjp2" for configuration "Debug"
set_property(TARGET gdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmopenjp2 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmopenjp2.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmopenjp2.dll"
  )

# Import target "gdcmcharls" for configuration "Debug"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmcharls.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmcharls.dll"
  )

# Import target "gdcmmd5" for configuration "Debug"
set_property(TARGET gdcmmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmmd5 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmmd5.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmmd5.dll"
  )

# Import target "gdcmzlib" for configuration "Debug"
set_property(TARGET gdcmzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gdcmzlib PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmzlib.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmzlib.dll"
  )

# Import target "socketxx" for configuration "Debug"
set_property(TARGET socketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(socketxx PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/socketxx.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/socketxx.dll"
  )

# Import target "gdcmCommon" for configuration "Release"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmCommon.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmmd5"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmCommon.dll"
  )

# Import target "gdcmDICT" for configuration "Release"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmDICT.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmDICT.dll"
  )

# Import target "gdcmDSED" for configuration "Release"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmDSED.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmzlib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmDSED.dll"
  )

# Import target "gdcmIOD" for configuration "Release"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIOD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmexpat"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIOD.dll"
  )

# Import target "gdcmMSFF" for configuration "Release"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMSFF.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjp2;gdcmcharls"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMSFF.dll"
  )

# Import target "gdcmMEXD" for configuration "Release"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;socketxx"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXD.dll"
  )

# Import target "gdcmjpeg8" for configuration "Release"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg8.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg8.dll"
  )

# Import target "gdcmjpeg12" for configuration "Release"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg12.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg12.dll"
  )

# Import target "gdcmjpeg16" for configuration "Release"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg16.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmjpeg16.dll"
  )

# Import target "gdcmexpat" for configuration "Release"
set_property(TARGET gdcmexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmexpat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmexpat.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmexpat.dll"
  )

# Import target "gdcmopenjp2" for configuration "Release"
set_property(TARGET gdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmopenjp2 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmopenjp2.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmopenjp2.dll"
  )

# Import target "gdcmcharls" for configuration "Release"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmcharls.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmcharls.dll"
  )

# Import target "gdcmmd5" for configuration "Release"
set_property(TARGET gdcmmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmmd5 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmmd5.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmmd5.dll"
  )

# Import target "gdcmzlib" for configuration "Release"
set_property(TARGET gdcmzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmzlib PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmzlib.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmzlib.dll"
  )

# Import target "socketxx" for configuration "Release"
set_property(TARGET socketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(socketxx PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/socketxx.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/socketxx.dll"
  )

# Import target "gdcmCommon" for configuration "MinSizeRel"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmCommon.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmmd5"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmCommon.dll"
  )

# Import target "gdcmDICT" for configuration "MinSizeRel"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmDICT.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmDICT.dll"
  )

# Import target "gdcmDSED" for configuration "MinSizeRel"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmDSED.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmzlib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmDSED.dll"
  )

# Import target "gdcmIOD" for configuration "MinSizeRel"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIOD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmexpat"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIOD.dll"
  )

# Import target "gdcmMSFF" for configuration "MinSizeRel"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMSFF.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjp2;gdcmcharls"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMSFF.dll"
  )

# Import target "gdcmMEXD" for configuration "MinSizeRel"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;socketxx"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXD.dll"
  )

# Import target "gdcmjpeg8" for configuration "MinSizeRel"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg8.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg8.dll"
  )

# Import target "gdcmjpeg12" for configuration "MinSizeRel"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg12.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg12.dll"
  )

# Import target "gdcmjpeg16" for configuration "MinSizeRel"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg16.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmjpeg16.dll"
  )

# Import target "gdcmexpat" for configuration "MinSizeRel"
set_property(TARGET gdcmexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmexpat PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmexpat.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmexpat.dll"
  )

# Import target "gdcmopenjp2" for configuration "MinSizeRel"
set_property(TARGET gdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmopenjp2 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmopenjp2.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmopenjp2.dll"
  )

# Import target "gdcmcharls" for configuration "MinSizeRel"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmcharls.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmcharls.dll"
  )

# Import target "gdcmmd5" for configuration "MinSizeRel"
set_property(TARGET gdcmmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmmd5 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmmd5.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmmd5.dll"
  )

# Import target "gdcmzlib" for configuration "MinSizeRel"
set_property(TARGET gdcmzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gdcmzlib PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmzlib.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmzlib.dll"
  )

# Import target "socketxx" for configuration "MinSizeRel"
set_property(TARGET socketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(socketxx PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/socketxx.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/socketxx.dll"
  )

# Import target "gdcmCommon" for configuration "RelWithDebInfo"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmCommon.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmmd5"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmCommon.dll"
  )

# Import target "gdcmDICT" for configuration "RelWithDebInfo"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmDICT.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmDICT.dll"
  )

# Import target "gdcmDSED" for configuration "RelWithDebInfo"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmDSED.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmzlib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmDSED.dll"
  )

# Import target "gdcmIOD" for configuration "RelWithDebInfo"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIOD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmexpat"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIOD.dll"
  )

# Import target "gdcmMSFF" for configuration "RelWithDebInfo"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMSFF.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjp2;gdcmcharls"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMSFF.dll"
  )

# Import target "gdcmMEXD" for configuration "RelWithDebInfo"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXD.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;socketxx"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXD.dll"
  )

# Import target "gdcmjpeg8" for configuration "RelWithDebInfo"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg8.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg8.dll"
  )

# Import target "gdcmjpeg12" for configuration "RelWithDebInfo"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg12.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg12.dll"
  )

# Import target "gdcmjpeg16" for configuration "RelWithDebInfo"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg16.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmjpeg16.dll"
  )

# Import target "gdcmexpat" for configuration "RelWithDebInfo"
set_property(TARGET gdcmexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmexpat PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmexpat.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmexpat.dll"
  )

# Import target "gdcmopenjp2" for configuration "RelWithDebInfo"
set_property(TARGET gdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmopenjp2 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmopenjp2.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmopenjp2.dll"
  )

# Import target "gdcmcharls" for configuration "RelWithDebInfo"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmcharls.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmcharls.dll"
  )

# Import target "gdcmmd5" for configuration "RelWithDebInfo"
set_property(TARGET gdcmmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmmd5 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmmd5.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmmd5.dll"
  )

# Import target "gdcmzlib" for configuration "RelWithDebInfo"
set_property(TARGET gdcmzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gdcmzlib PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmzlib.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmzlib.dll"
  )

# Import target "socketxx" for configuration "RelWithDebInfo"
set_property(TARGET socketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(socketxx PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/socketxx.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/socketxx.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
