# CMake generated Testfile for 
# Source directory: C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx
# Build directory: C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/Testing/Source/InformationObjectDefinition/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestTableReader "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestTableReader")
  set_tests_properties(TestTableReader PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestTableReader "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestTableReader")
  set_tests_properties(TestTableReader PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestTableReader "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestTableReader")
  set_tests_properties(TestTableReader PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestTableReader "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestTableReader")
  set_tests_properties(TestTableReader PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestTableReader NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestTable "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestTable")
  set_tests_properties(TestTable PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestTable "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestTable")
  set_tests_properties(TestTable PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestTable "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestTable")
  set_tests_properties(TestTable PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestTable "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestTable")
  set_tests_properties(TestTable PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestTable NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestTableEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestTableEntry")
  set_tests_properties(TestTableEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestTableEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestTableEntry")
  set_tests_properties(TestTableEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestTableEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestTableEntry")
  set_tests_properties(TestTableEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestTableEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestTableEntry")
  set_tests_properties(TestTableEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestTableEntry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestType "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestType")
  set_tests_properties(TestType PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestType "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestType")
  set_tests_properties(TestType PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestType "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestType")
  set_tests_properties(TestType PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestType "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestType")
  set_tests_properties(TestType PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestType NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestModule "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestModule")
  set_tests_properties(TestModule PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestModule "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestModule")
  set_tests_properties(TestModule PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestModule "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestModule")
  set_tests_properties(TestModule PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestModule "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestModule")
  set_tests_properties(TestModule PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestModule NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestModules "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestModules")
  set_tests_properties(TestModules PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestModules "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestModules")
  set_tests_properties(TestModules PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestModules "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestModules")
  set_tests_properties(TestModules PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestModules "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestModules")
  set_tests_properties(TestModules PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestModules NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestModuleEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestModuleEntry")
  set_tests_properties(TestModuleEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestModuleEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestModuleEntry")
  set_tests_properties(TestModuleEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestModuleEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestModuleEntry")
  set_tests_properties(TestModuleEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestModuleEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestModuleEntry")
  set_tests_properties(TestModuleEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestModuleEntry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestNestedModuleEntries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestNestedModuleEntries")
  set_tests_properties(TestNestedModuleEntries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestNestedModuleEntries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestNestedModuleEntries")
  set_tests_properties(TestNestedModuleEntries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestNestedModuleEntries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestNestedModuleEntries")
  set_tests_properties(TestNestedModuleEntries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestNestedModuleEntries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestNestedModuleEntries")
  set_tests_properties(TestNestedModuleEntries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestNestedModuleEntries NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestIODEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestIODEntry")
  set_tests_properties(TestIODEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestIODEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestIODEntry")
  set_tests_properties(TestIODEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestIODEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestIODEntry")
  set_tests_properties(TestIODEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestIODEntry "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestIODEntry")
  set_tests_properties(TestIODEntry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestIODEntry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestIOD "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestIOD")
  set_tests_properties(TestIOD PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestIOD "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestIOD")
  set_tests_properties(TestIOD PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestIOD "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestIOD")
  set_tests_properties(TestIOD PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestIOD "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestIOD")
  set_tests_properties(TestIOD PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestIOD NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestIODs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestIODs")
  set_tests_properties(TestIODs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestIODs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestIODs")
  set_tests_properties(TestIODs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestIODs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestIODs")
  set_tests_properties(TestIODs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestIODs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestIODs")
  set_tests_properties(TestIODs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestIODs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestDefs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestDefs")
  set_tests_properties(TestDefs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestDefs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestDefs")
  set_tests_properties(TestDefs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestDefs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestDefs")
  set_tests_properties(TestDefs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestDefs "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestDefs")
  set_tests_properties(TestDefs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestDefs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestPatient "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestPatient")
  set_tests_properties(TestPatient PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestPatient "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestPatient")
  set_tests_properties(TestPatient PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestPatient "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestPatient")
  set_tests_properties(TestPatient PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestPatient "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestPatient")
  set_tests_properties(TestPatient PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestPatient NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestSeries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestSeries")
  set_tests_properties(TestSeries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestSeries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestSeries")
  set_tests_properties(TestSeries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestSeries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestSeries")
  set_tests_properties(TestSeries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestSeries "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestSeries")
  set_tests_properties(TestSeries PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestSeries NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestStudy "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestStudy")
  set_tests_properties(TestStudy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestStudy "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestStudy")
  set_tests_properties(TestStudy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestStudy "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestStudy")
  set_tests_properties(TestStudy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestStudy "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestStudy")
  set_tests_properties(TestStudy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestStudy NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestDefinedTerms "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestDefinedTerms")
  set_tests_properties(TestDefinedTerms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestDefinedTerms "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestDefinedTerms")
  set_tests_properties(TestDefinedTerms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestDefinedTerms "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestDefinedTerms")
  set_tests_properties(TestDefinedTerms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestDefinedTerms "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestDefinedTerms")
  set_tests_properties(TestDefinedTerms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestDefinedTerms NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestEnumeratedValues "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestEnumeratedValues")
  set_tests_properties(TestEnumeratedValues PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestEnumeratedValues "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestEnumeratedValues")
  set_tests_properties(TestEnumeratedValues PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestEnumeratedValues "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestEnumeratedValues")
  set_tests_properties(TestEnumeratedValues PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestEnumeratedValues "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestEnumeratedValues")
  set_tests_properties(TestEnumeratedValues PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestEnumeratedValues NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestUsage "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmIODTests.exe" "TestUsage")
  set_tests_properties(TestUsage PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestUsage "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmIODTests.exe" "TestUsage")
  set_tests_properties(TestUsage PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestUsage "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmIODTests.exe" "TestUsage")
  set_tests_properties(TestUsage PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestUsage "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmIODTests.exe" "TestUsage")
  set_tests_properties(TestUsage PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;45;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/InformationObjectDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestUsage NOT_AVAILABLE)
endif()
