# CMake generated Testfile for 
# Source directory: C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx
# Build directory: C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/Testing/Source/MessageExchangeDefinition/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestPresentationContextRQ "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestPresentationContextRQ")
  set_tests_properties(TestPresentationContextRQ PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestPresentationContextRQ "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestPresentationContextRQ")
  set_tests_properties(TestPresentationContextRQ PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestPresentationContextRQ "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestPresentationContextRQ")
  set_tests_properties(TestPresentationContextRQ PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestPresentationContextRQ "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestPresentationContextRQ")
  set_tests_properties(TestPresentationContextRQ PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestPresentationContextRQ NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestQueryFactory "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestQueryFactory")
  set_tests_properties(TestQueryFactory PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestQueryFactory "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestQueryFactory")
  set_tests_properties(TestQueryFactory PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestQueryFactory "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestQueryFactory")
  set_tests_properties(TestQueryFactory PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestQueryFactory "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestQueryFactory")
  set_tests_properties(TestQueryFactory PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestQueryFactory NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestULConnectionManager "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestULConnectionManager")
  set_tests_properties(TestULConnectionManager PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestULConnectionManager "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestULConnectionManager")
  set_tests_properties(TestULConnectionManager PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestULConnectionManager "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestULConnectionManager")
  set_tests_properties(TestULConnectionManager PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestULConnectionManager "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestULConnectionManager")
  set_tests_properties(TestULConnectionManager PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestULConnectionManager NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestSCUValidation "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestSCUValidation")
  set_tests_properties(TestSCUValidation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestSCUValidation "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestSCUValidation")
  set_tests_properties(TestSCUValidation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestSCUValidation "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestSCUValidation")
  set_tests_properties(TestSCUValidation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestSCUValidation "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestSCUValidation")
  set_tests_properties(TestSCUValidation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestSCUValidation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestEcho "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestEcho")
  set_tests_properties(TestEcho PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestEcho "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestEcho")
  set_tests_properties(TestEcho PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestEcho "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestEcho")
  set_tests_properties(TestEcho PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestEcho "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestEcho")
  set_tests_properties(TestEcho PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestEcho NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestFind "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestFind")
  set_tests_properties(TestFind PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestFind "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestFind")
  set_tests_properties(TestFind PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestFind "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestFind")
  set_tests_properties(TestFind PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestFind "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestFind")
  set_tests_properties(TestFind PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestFind NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestFindStudyRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestFindStudyRootQuery")
  set_tests_properties(TestFindStudyRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestFindStudyRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestFindStudyRootQuery")
  set_tests_properties(TestFindStudyRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestFindStudyRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestFindStudyRootQuery")
  set_tests_properties(TestFindStudyRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestFindStudyRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestFindStudyRootQuery")
  set_tests_properties(TestFindStudyRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestFindStudyRootQuery NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TestFindPatientRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Debug/gdcmMEXDTests.exe" "TestFindPatientRootQuery")
  set_tests_properties(TestFindPatientRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TestFindPatientRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/Release/gdcmMEXDTests.exe" "TestFindPatientRootQuery")
  set_tests_properties(TestFindPatientRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TestFindPatientRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/MinSizeRel/gdcmMEXDTests.exe" "TestFindPatientRootQuery")
  set_tests_properties(TestFindPatientRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TestFindPatientRootQuery "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm/bin/RelWithDebInfo/gdcmMEXDTests.exe" "TestFindPatientRootQuery")
  set_tests_properties(TestFindPatientRootQuery PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;55;add_test;C:/Users/lukas/Documents/Bachelorarbeit/VulkanBase/lib/gdcm-3.0.10/Testing/Source/MessageExchangeDefinition/Cxx/CMakeLists.txt;0;")
else()
  add_test(TestFindPatientRootQuery NOT_AVAILABLE)
endif()
